import type { BrowserShortcutAction } from '../../shared/browser.js';

export type BrowserShortcutInput = {
  type: string;
  key: string;
  meta?: boolean;
  control?: boolean;
  shift?: boolean;
  alt?: boolean;
};

export type BrowserClipboardCommand = 'cut' | 'copy' | 'paste';

export function resolveClipboardShortcutCommand(
  keys: string[],
  isMac = process.platform === 'darwin',
): BrowserClipboardCommand | null {
  const normalized = keys.map((key) => key.toLowerCase());
  const control = normalized.some((key) => key === 'control' || key === 'ctrl');
  const meta = normalized.some((key) => key === 'meta' || key === 'command' || key === 'cmd');
  const modified = isMac ? meta : control;
  const oppositePlatformModifier = isMac ? control : meta;
  const shift = normalized.includes('shift');
  const alt = normalized.includes('alt');
  if (modified && !oppositePlatformModifier && !alt) {
    // Shift+V is Chromium's paste-as-plain-text variant and still reads the
    // system clipboard. Shift+C/X are commonly DevTools/extension shortcuts,
    // so do not steal them from the page as edit commands.
    if (normalized.includes('v')) return 'paste';
    if (!shift && normalized.includes('c')) return 'copy';
    if (!shift && normalized.includes('x')) return 'cut';
    if (!isMac && !shift && normalized.includes('insert')) return 'copy';
  }

  // Chromium also supports these legacy editing accelerators on non-macOS
  // platforms. Resolve them to the same guarded native commands.
  if (!isMac && !modified && !oppositePlatformModifier && !alt && shift && normalized.includes('insert')) {
    return 'paste';
  }
  if (!isMac && !modified && !oppositePlatformModifier && !alt && shift && normalized.includes('delete')) {
    return 'cut';
  }
  return null;
}

export function isClipboardShortcutKeys(keys: string[], isMac = process.platform === 'darwin'): boolean {
  return resolveClipboardShortcutCommand(keys, isMac) !== null;
}

/** Application-menu accelerators must never be generated by an assistant.
 * Electron routes modifier chords and platform function-key accelerators to
 * the focused window before a remote page can safely contain their effects.
 * User keyboard input remains unrestricted; this gate applies only to
 * synthetic `browser_action(kind="press")` input. */
export function isApplicationAcceleratorShortcutKeys(keys: string[]): boolean {
  const normalized = keys.map((key) => key.toLowerCase());
  if (normalized.some((key) => ['control', 'ctrl', 'meta', 'command', 'cmd', 'alt'].includes(key))) return true;
  return normalized.some((key) => /^f(?:[1-9]|1\d|2[0-4])$/.test(key));
}

/** True when synthetic page input would be intercepted as Browser chrome on
 * either Cmd-based or Ctrl-based platforms. AI actions must not accidentally
 * turn these into user-provenance tab/navigation commands. */
export function isReservedBrowserShortcutKeys(keys: string[]): boolean {
  if (keys.length === 0) return false;
  const normalized = keys.map((key) => key.toLowerCase());
  const key = keys.at(-1) ?? '';
  const input: BrowserShortcutInput = {
    type: 'keyDown',
    key,
    meta: normalized.some((item) => item === 'meta' || item === 'command' || item === 'cmd'),
    control: normalized.some((item) => item === 'control' || item === 'ctrl'),
    shift: normalized.includes('shift'),
    alt: normalized.includes('alt'),
  };
  return resolveBrowserShortcut(input, true) !== null || resolveBrowserShortcut(input, false) !== null;
}

export function shouldFocusBrowserChrome(action: BrowserShortcutAction): boolean {
  return (
    action === 'new-tab' ||
    action === 'focus-url' ||
    action === 'find' ||
    action === 'find-next' ||
    action === 'find-previous'
  );
}

export function resolveBrowserShortcut(
  input: BrowserShortcutInput,
  isMac = process.platform === 'darwin',
): { action: BrowserShortcutAction; index?: number } | null {
  if (input.type !== 'keyDown') return null;
  if (input.key === 'Escape') return { action: 'stop' };
  const mod = isMac ? input.meta : input.control;
  if (!mod) {
    // Alt+Left/Right is browser history on Windows/Linux. On macOS, Option+
    // arrows are ordinary word-navigation commands, and Alt+Shift+arrows are
    // reserved by Kai's tab strip for keyboard reordering on every platform.
    if (!isMac && input.alt && !input.shift && input.key === 'ArrowLeft') return { action: 'back' };
    if (!isMac && input.alt && !input.shift && input.key === 'ArrowRight') return { action: 'forward' };
    return null;
  }
  const key = input.key.toLowerCase();
  if (input.shift) {
    if (key === 't') return { action: 'reopen-tab' };
    if (key === 'r') return { action: 'hard-reload' };
    if (key === 'g') return { action: 'find-previous' };
    return null;
  }
  if (key === 't') return { action: 'new-tab' };
  if (key === 'w') return { action: 'close-tab' };
  if (key === 'l') return { action: 'focus-url' };
  if (key === 'r') return { action: 'reload' };
  if (key === 'f') return { action: 'find' };
  if (key === 'g') return { action: 'find-next' };
  // Keep the unambiguous bracket shortcuts at the native-page boundary.
  // Cmd/Ctrl+arrows are caret movement in editable controls; BrowserPanel may
  // additionally claim them when a non-editable React chrome control has focus.
  if (key === '[') return { action: 'back' };
  if (key === ']') return { action: 'forward' };
  if (key === '=' || key === '+') return { action: 'zoom-in' };
  if (key === '-') return { action: 'zoom-out' };
  if (key === '0') return { action: 'zoom-reset' };
  if (key >= '1' && key <= '8') return { action: 'tab-number', index: Number(key) - 1 };
  if (key === '9') return { action: 'tab-last' };
  return null;
}
