/**
 * Aithena V3 Proactive Recommendations — type definitions for the renderer.
 *
 * Recommendations are generated by Aithena's proactive evaluator during workflow
 * execution and broadcast to the renderer via plugin events.
 */

export interface Recommendation {
  id: string;
  type: 'risk' | 'next_action' | 'context' | 'learning' | 'escalation';
  title: string;
  rationale: string;
  confidence: 'low' | 'medium' | 'high';
  suggested_action: string;
  trigger: string;
  source_signals: string[];
  status: 'open' | 'accepted' | 'dismissed' | 'expired';
  expires_at: string | null;
  /** Legacy compat — some API responses include 'content' instead of 'rationale'. */
  content?: string;
}

export interface ConsumedRecommendation {
  id: string;
  title: string;
  type: string;
  confidence: string;
  action: 'learned' | 'injected_context' | 'paused_execution' | 'suggested_action';
  timestamp?: string;
}
